### ISSUE TITLE
Texture issue on model

### ISSUE THREAD

**Issue by developerPS4Pro** [grimdoomer/DeadRisingArcTool#3]
Hi, Texture problem on the model there is no texture on the face of this Model evh001.rModel
hair problem also on evh000.rModel I can't read the animations also possible to support them also the BGM. Ast I have a script for xbox 360 with Noesis possible to make your tool compatible with thanks if I can just read the animation, voices, bgm. as well as textures, I have also seen other problems on all other Model em and PL00 PL01

I can give you the scripts xbox 360 https://mega.nz/folder/gnAkjbwB#vzLcf2ZTzYqZkWM-6hu7Yg
it only works with Noesis support motion .lmt the texture and the Model also the animations would be great. batch convert model to .evh001.mod THANKS

XISO 1.06 to extract Xbox 360 ISO https://mega.nz/file/M650BZzL#eTPtZ2F-sD1jsMogJ_z0ikdgBx5MJtBoB23uxrNO1GI

**Comment by grimdoomer** [comment]
Xbox 360 support has been deprecated, closing this issue as non-actionable.
